# Many numpy problems:


<h3>1. How to create a boolean array?</h3>
<strong></strong>

In [1]:
import numpy as np
#1 
x = np.full((3,3),True,dtype=bool)
print(x)
#2
x = np.ones([3,3], dtype=bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


<h3>2. How to extract items that satisfy a given condition from 1D array?</h3>
<strong>Q. Extract all odd numbers from arr
</strong>

In [2]:
arr = np.arange(10)
b = arr %2 == 1
print(arr[b])


[1 3 5 7 9]


<h3>3. How to replace items that satisfy a condition with another value in numpy array?</h3>
<strong> Q. Replace all odd numbers in arr with -1</strong>

In [5]:
arr[arr % 2 ==1] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


<h3>4. How to replace items that satisfy a condition without affecting the original array?</h3>
<strong>Q. Replace all odd numbers in arr with -1 without changing arr</strong>

In [7]:
#1
arr = np.arange(10)
out = arr.copy()
out[out %2 ==1]=-1
print('arr:',arr)
print('out:',out)
#2
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1,arr)
print(arr)
print(out)

arr: [0 1 2 3 4 5 6 7 8 9]
out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


<h3>5. How to reshape an array?</h3>
<strong>. Convert a 1D array to a 2D array with 2 rows</strong>

In [8]:
#1
arr = np.arange(10)
arr2d = np.reshape(arr, [2,5])
print(arr2d)
#2
arr2d = arr.reshape(2 , -1)
print(arr2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


<h3>6.  How to stack two arrays vertically?</h3>
</strong>Q. Stack arrays a and b vertically<strong>

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print('a:',a)
print('b:',b)
print('concatenate version:',np.vstack([a,b]))

a: [[0 1 2 3 4]
 [5 6 7 8 9]]
b: [[1 1 1 1 1]
 [1 1 1 1 1]]
concatenate version: [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


<h3>6. How to generate custom sequences in numpy without hardcoding?</h3>
<strong>Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.</strong>


In [10]:
a = np.array([1,2,3])
print(np.r_[a.repeat(3),np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


<h3>8. How to remove from one array those items that exist in another?</h3>
<strong>Q. From array a remove all items present in array b<strong>

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


<h3>9. How to get the positions where elements of two arrays match?</h3>
<strong>Q. Get the positions where elements of a and b match</strong>

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))

(array([1, 3, 5, 7]),)


<h3>10. How to extract all numbers between a given range from a numpy array?</h3>
<strong>Q. Get all items between 5 and 10 from a.</strong>

In [5]:
# 1

a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a>=5) & (a <= 10))

print('method 1:',a[index])

# 2

print('method 2:',a[np.where(np.logical_and(a>=5 , a<=10))])

method 1: [ 6  9 10]
method 2: [ 6  9 10]


<h3> 10. How to make a python function that handles scalars to work on numpy arrays?</h3>
<strong>Q. Convert the function maxx that works on two scalars, to work on two arrays.</strong>

In [4]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)


5

In [6]:
max_vectorize = np.vectorize(maxx,otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

max_vectorize(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

<h3>11. How to swap two columns in a 2d numpy array?</h3>
<strong>Q. Swap columns 1 and 2 in the array arr.</strong>

In [9]:
# Input
arr = np.arange(9).reshape(3,3)
arr

# Solution
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

<h3>12. How to reverse the rows of a 2D array?</h3>
<strong>Q. Reverse the rows of a 2D array arr.</strong>

In [13]:
arr = np.arange(9).reshape(3,3)
print("arr:",arr)
print('Reversed arr:',arr[::-1])


arr: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed arr: [[6 7 8]
 [3 4 5]
 [0 1 2]]


<h3>13. How to reverse the columns of a 2D array?</h3>
<strong>Q. Reverse the columns of a 2D array arr.</strong>

In [14]:
print(arr[::1,::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


<h3>14. How to create a 2D array containing random floats between 5 and 10?</h3>
<strong>Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.</strong>

In [17]:
# Input
arr = np.arange(9).reshape(3,3)

# 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print('rand array:',rand_arr)

# 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print('rand array:',rand_arr)

rand array: [[5.91771466 6.93351802 8.48131558]
 [6.69149558 8.76366927 9.46647579]
 [8.69577068 5.27563244 6.03518783]
 [8.27524664 5.1061422  5.13967207]
 [9.16087266 6.28068525 8.50865925]]
rand array: [[5.19623698 7.112303   5.41319515]
 [9.97272673 9.29025863 9.92670073]
 [5.45830823 6.34853142 9.33788045]
 [8.55456961 7.76251318 5.84556278]
 [8.40639485 6.1489978  7.79437803]]
